name: digital-signature

services:
  root-ca:
    build: .
    command: bash
    tty: true
    volumes:
      - ./volumes/root-ca/app:/app
      - ./volumes/share:/app/share
  my-server:
    build: .
    command: bash
    tty: true
    volumes:
      - ./volumes/my-server/app:/app
      - ./volumes/share:/app/share
  my-client:
    build: .
    command: bash
    tty: true
    volumes:
      - ./volumes/my-client/app:/app
      - ./volumes/share:/app/share
