name: bind-servers

services:
  xss:
    image: node:26.5.1
    container_name: xss
    working_dir: /app
    ports:
      - 3000:3000
    command: ["node", "./server.js"]
    tty: true
    restart: always
    volumes:
      - ./volumes/app:/app
