options {
  // ⭐️以下、オリジナルの設定
  // 送信元ポートを固定化して確率を上げる（古いDNSの挙動再現）
  query-source address * port 53000;
    // 上位のDNSサーバーに転送する場合の設定
  forwarders {
      192.168.1.11;
  };
  // forward only: 指定したフォワーダーでのみ解決を試み、失敗してもルートサーバーに直接聞きに行かない
  // forward first: （デフォルト）フォワーダーで失敗した場合、自身でルートサーバー等へ聞きに行く
  forward only;
  // 上位DNSサーバーへの問い合わせタイムアウト（秒）
  resolver-query-timeout 60;
  // （必要に応じて）全体の最大応答待ち時間もあわせて伸ばす場合
  max-retry-time 60;
  dnssec-validation no;
  // ⭐️以上、オリジナルの設定

  directory "/var/cache/bind";

  // 外部からのDNSリクエストを受け付けるインターフェース
  listen-on port 53 { any; };
  listen-on-v6 { none; };

  // キャッシュ（再帰検索）問い合わせを許可するネットワーク
  allow-query {
      localhost;
      10.0.0.0/8;
      172.16.0.0/12;
      192.168.0.0/16;
  };

  // 再帰検索を有効化（キャッシュサーバーとして動かす設定）
  recursion yes;
  allow-recursion {
      localhost;
      10.0.0.0/8;
      172.16.0.0/12;
      192.168.0.0/16;
  };

  // DNSSECの検証を有効化
  //dnssec-validation auto;

  // バージョン情報の隠蔽（セキュリティ対策）
  version "none";
};

logging {
    // default_stderr はBINDにあらかじめ用意されている標準エラー出力用チャンネルです
    category default      { default_stderr; };
    category general      { default_stderr; };
    category queries      { default_stderr; };
    category query-errors { default_stderr; };
    category resolver     { default_stderr; };
};