name: reverse-proxy-for-sso

services:
  reverse-proxy:
    image: node:26.5.0
    ports:
      - 3000:3000
    working_dir: /app
    command: ["node", "app.js"]
    volumes:
      - ./volumes/reverse-proxy/app:/app
  back-server1:
    image: node:26.5.0
    ports:
      - 3001:3001
    working_dir: /app
    command: ["node", "app.js"]
    volumes:
      - ./volumes/back-server1/app:/app
  back-server2:
    image: node:26.5.0
    ports:
      - 3002:3002
    working_dir: /app
    command: ["node", "app.js"]
    volumes:
      - ./volumes/back-server2/app:/app
