;か#からコメントが始まる。
; /etc/resolv.confは、名前解決を行うために参照するDNSサーバの情報を定義するファイル。
nameserver 192.168.1.11 ; 名前解決を問い合わせるDNSサーバーのIPアドレス。通常はDNSキャッシュサーバを指す。
search example1.test ;ドメイン名（例: example.com）を指定すると、ホスト名だけ（例: server1）で通信しようとした際に、自動的にそのドメイン名を補って検索してくれます。
