name: waf-lab

services:
  # --- 1. 脆弱性Webアプリ ---
  juice-shop:
    image: bkimminich/juice-shop:latest
    ports:
      - "3000:3000"

  # --- 2. WAF (OWASP ModSecurity / Nginx) ---
  waf-loose:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "80:8080"
    environment:
      - BACKEND=http://juice-shop:3000
      - PORT=8080
      - PARANOIA=1
      - SEC_RULE_ENGINE=DetectionOnly
    depends_on:
      - juice-shop
  waf-strict:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "81:8080"
    environment:
      - BACKEND=http://juice-shop:3000
      - PORT=8080
      - PARANOIA=4
      - SEC_RULE_ENGINE=On # Set to 'DetectionOnly' to log without blocking
    depends_on:
      - juice-shop
